capture: Don't define static get_unix_sdl_type fxn on _WIN32
The static function get_unix_sdl_type is not used when
_WIN32 is defined, leading to an warning when compiling on
Windows with some compilers, e.g., clang-cl, gcc (MSYS2),
or cross-compiling:

https://github.com/wireshark/wireshark/actions/runs/24329372102/job/71031456883

D:/a/wireshark/wireshark/capture/capture-pcap-util.c:184:12: error: 'get_unix_sdl_type' defined but not used [-Werror=unused-function]
  184 | static int get_unix_sdl_type(const char *ifname _U_)
      |            ^~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors

Fixup 6ef0555e64a5d18d27fdacee9b576b879c12c7b0

AI-Assisted: no