CMake: Use -Wstack-usage instead of -Wframe-larger-than
The latter is a greatest lower bound, the former is an upper bound.
They differ primarily in the treatment of alloca and VLAs. There
are no warnings with -Wstack-usage currently, but before commit
a492f2f18944cb7b36b5b33cd3a35b606f39a1ab the use of g_alloca with
a variable produces:

/home/johnthacker/git/wireshark/ui/text_import.c: In function ‘parse_seqno’:
/home/johnthacker/git/wireshark/ui/text_import.c:1204:6: error: stack usage might be unbounded [-Werror=stack-usage=]
 1204 | void parse_seqno(const unsigned char* start_field, const unsigned char* end_field) {
      |      ^~~~~~~~~~~
cc1: all warnings being treated as errors

Compare:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstack-usage
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wframe-larger-than_003d

Ping #19995

AI-Assisted: no